name: Survivalgames
version: ${project.version}
main: survivalgames.main.SurvivalMain
api-version: 1.15
commands:
  sg:
    description: Help Command.
    usage: /<command>
  sg create:
    description: Create a new arena.
    usage: /<command> [name of arena]
  sg setspawn:
    description: Set an individual spawning location for an arena.
    usage: /<command> [name of arena]
  sg delete:
    description: Delete an arena
    usage: /<command> [name of arena]
  sg join:
    description: Join an arena.
    usage: /<command> [name of arena]
  sg start:
    description: Start a game.
    usage: /<command> [name of arena]
depend: [WorldEdit]